### ISSUE TITLE
[Add] Demographics Survey

### ISSUE THREAD

**Issue by aridyckovsky** [comanlab/surveys#1]
Add a new survey to the repository according to the instructions in [the package README.md](https://github.com/comanlab/surveys#readme).

# Survey Title

Demographics Survey

## Survey Source

TBD

## Survey Overview

Questions for demographic information that are relatively static over time.

## Aggregation/scoring function

None.

# Tasks

- [ ] Create a new folder in surveys w/ descriptive, easy-to-read name `myNewSurvey/`
- [ ] Create SurveyJS .json file (_e.g._ `myNewSurvey/myNewSurvey.json`)
  - [ ] Change the default completion page to a blank page (`"showCompletedPage": false`)
- [ ] Create a .bib file citing your references for the survey (_always:_ `myNewSurvey/references.bib`)
- [ ] Create file with function to aggregate survey data (_e.g._ `myNewSurvey.score.js`)
- [ ] Create a cypress test of the survey (e.g. `myNewSurvey.cy.jsx`)
  - [ ] Include a line to take a screenshot at the end of every page
- [ ] Create a readme markdown file to document (_always:_ `myNewSurvey/README.md`)
  - [ ] Include relevant screenshots
- [ ] Update the package minor version
- [ ] Rebuild the package using `npm run build` to update SHAs
- [ ] Create PR and link to this issue
